services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
    volumes:
      - /home/username/docker/jellyfin/config:/config
      - /home/username/docker/jellyfin/cache:/cache
      - /home/username/media:/media:ro
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    ports:
      - 5055:5055
    volumes:
      - /home/username/docker/seerr/config:/app/config
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - /home/username/docker/sonarr/config:/config
      - /home/username/media:/data
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - /home/username/docker/qbittorrent/config:/config
      - /home/username/media:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped
