services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
    volumes:
      - /home/fill-usr/docker/jellyfin/config:/config
      - /home/fill-usr/docker/jellyfin/cache:/cache
      - /home/fill-usr/media:/media:ro
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    ports:
      - 5055:5055
    volumes:
      - /home/fill-usr/docker/seerr/config:/app/config
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - /home/fill-usr/docker/sonarr/config:/config
      - /home/fill-usr/media:/data
    restart: unless-stopped

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - /home/fill-usr/docker/radarr/config:/config
      - /home/fill-usr/media:/data
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - /home/fill-usr/docker/qbittorrent/config:/config
      - /home/fill-usr/media:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: jellyfin
    environment:
      - TS_AUTHKEY=tskey-auth-kL7dHMnAop11CNTRL-xxFRPKKEysB44LUTRR6ysBzzy3oCxNZg
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /home/fill-usr/docker/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
