Sonarr:
    image: ghcr.io/hotio/sonarr
    volumes:
        - /home/username/docker/sonarr/config:/config
        - /home/username/media:/data
    environment:
        - PUID=111
        - PGID=321
        - UMASK=002
